# Generated by Django 3.2.9 on 2021-11-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_usuario',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=20, verbose_name='Nombre del plan')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Nombre del plan')),
                ('precio', models.FloatField(default=0.0, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=20, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Numero de documento')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Numero de Telefono')),
                ('correo_electronico', models.EmailField(max_length=100, verbose_name='Correo')),
                ('fecha', models.DateField(max_length=50, verbose_name='Fecha')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_usuario', to='AppReservas.plan_usuario')),
            ],
        ),
    ]
