# Generated by Django 3.2.9 on 2021-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_documento',
            field=models.FloatField(max_length=20, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.FloatField(max_length=15, verbose_name='Numero de Telefono'),
        ),
    ]
