# Generated by Django 3.2.7 on 2021-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservas', '0002_auto_20211120_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_usuario',
            name='jornada',
            field=models.CharField(choices=[('Diurno', 'diurno'), ('Nocturno', 'nocturno')], default='Diurno', max_length=10, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='plan_usuario',
            name='nombre_plan',
            field=models.CharField(max_length=50, verbose_name='Nombre del plan'),
        ),
    ]
