# Generated by Django 3.2.7 on 2021-12-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservas', '0003_auto_20211123_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_usuario',
            name='url',
            field=models.CharField(default='https://elcomercio.pe/resizer/TGCsuHf4e88fBOhhEUbfaHgHs9A=/560x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/ZPAAAE7JYRBETISIFG3E77ZACU.png', max_length=2083, verbose_name='Nombre del plan'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Numero de Telefono'),
        ),
    ]
